version: "3.8"
services:
  app:
    build: .
    restart: always
    environment:
      - spring.datasource.url=jdbc:postgresql://postgresdb:5432/pizza_app_java?allowPublicKeyRetrieval=true
    ports:
      - "3000:3000"
    depends_on:
      - postgresdb

  postgresdb:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "pizza_app_java"